# Generated by Django 4.2.6 on 2023-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_inventory_barcode_barecode"),
    ]

    operations = [
        migrations.AddField(
            model_name="barecode",
            name="barcode_status",
            field=models.IntegerField(
                choices=[
                    (0, "generated"),
                    (1, "sticked"),
                    (2, "shipped"),
                    (3, "returned"),
                ],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
