# Generated by Django 4.2.6 on 2023-11-18 20:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_size_size_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BareCode",
            new_name="BarCode",
        ),
    ]
